version: 2
updates:
  - package-ecosystem: "npm" # or "maven", "pip", etc.
    directory: "/" # location of package manifest
    schedule:
      interval: "weekly" # or 
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
