name: "🌟 Feature Request"
description: "Suggest a new feature or improvement"
labels: ["enhancement"]

body:
  - type: input
    attributes:
      label: "Feature Title"
      placeholder: "E.g., Add dark mode"

  - type: textarea
    attributes:
      label: "Description"
      placeholder: "Why this feature would be useful"

  - type: textarea
    attributes:
      label: "Additional context"
