name: "🧹 Technical Debt"
description: "Log an internal improvement or refactor"
labels: ["tech-debt"]

body:
  - type: input
    attributes:
      label: "Component/Area"
      placeholder: "E.g., Auth module"

  - type: textarea
    attributes:
      label: "What needs to be improved?"

  - type: textarea
    attributes:
      label: "Reason / Impact"
      placeholder: "Explain why this tech debt matters"
 