name: Synthetic Monitoring with k6

on:
  push:
    branches:
      - main

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y gnupg software-properties-common
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 33B4659183DDA525
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install -y k6

      - name: Run k6 test
        run: k6 run monitor/login-check.js
