name: Auto Add Issue to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to GitHub project
        uses: actions/github-script@v6
        with:
          project-url: https://github.com/users/thilakshitha/projects/2
          github-token: ${{ secrets.GH_PAT }}
