name: Move Issues to Project

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  move_issues:
    runs-on: windows-latest
    steps:
      - name: Move Issue to 'To Do' Column
        uses: peter-evans/project-card@v1
        with:
          project-url: https://github.com/users/thilakshitha/projects/1/views/1

          column-name: 'To Do'
          issue-number: ${{ github.event.issue.number }}
